version: '3.8'

services:
  bot:
    container_name: bot
    build: .
  db:
    container_name: db
    ports:
      - '5432'
    environment:
      - POSTGRES_PASSWORD=enigma12
      - POSTGRES_USER=postgres
    image: postgres:alpine3.19